version: "2"

services:
 php-fpm:
    container_name: php-fpm
    build:
          context: .
          dockerfile: Dockerfile
    image: quay.io/cashrewards/php-base-ms:local
    volumes:
     - ./src:/var/www/html
    ports:
     - "9000:9000"

 nginx:
    container_name: nginx
    image: nginx
    ports:
      - "81:80"
    links:
      - "php-fpm"
    volumes_from:
      - php-fpm:ro
        # from search-php-fpm container
        # /etc/nginx/conf.d/default.conf
        # /var/www/html [ image default = /usr/share/nginx/html ]

 mysql:
   container_name: mysql
   image: mysql
   restart: always
   environment:
     MYSQL_DATABASE: CRutils
     MYSQL_ROOT_PASSWORD: “<YourStrong!Passw0rd>”
   ports:
     - “3306:3306"
