version: "2"

services:
 php-fpm:
    container_name: crutils-metrics-php-fpm
    build:
          context: .
          dockerfile: Dockerfile
    image: quay.io/cashrewards/crutils-metrics:local
    volumes:
     - ./src:/var/www/html
    ports:
     - "9000:9000"

 nginx:
    container_name: crutils-metrics-nginx
    image: nginx
    ports:
      - "81:80"
    links:
      - "php-fpm"
    volumes_from:
      - php-fpm:ro
        # from search-php-fpm container
        # /etc/nginx/conf.d/default.conf
        # /var/www/html [ image default = /usr/share/nginx/html ]

 mysql:
    container_name: crutils-metrics-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: CRutils_metrics
      MYSQL_ROOT_PASSWORD: "<YourStrong!Passw0rd>"
    ports:
      - "3306:3306"
    logging:
      driver: none