CREATE TABLE [dbo].[Client] (
    [ClientId]            INT             IDENTITY (1000000, 1) NOT NULL,
    [ClientName]          NVARCHAR (500)  NOT NULL,
    [WebsiteName]         NVARCHAR (500)  NOT NULL,
    [RewardName]          NVARCHAR (500)  NOT NULL,
    [ManagementName]      NVARCHAR (500)  NULL,
    [ProviderName]        NVARCHAR (500)  NULL,
    [HostedUrl]           NVARCHAR (500)  NOT NULL,
    [DevHostedUrl]        NVARCHAR (500)  NULL,
    [Status]              INT             NOT NULL,
    [IsGstRegistered]     BIT             NOT NULL,
    [ClientLayoutThemeId] INT             NOT NULL,
    [ClientProgramTypeId] INT             NOT NULL,
    [ClientAccessTypeId]  INT             NOT NULL,
    [ClientRewardTypeId]  INT             NOT NULL,
    [ClientTypeId]        INT             NOT NULL,
    [DefaultCommPct]      DECIMAL (18, 2) NOT NULL,
    [MemberCommPct]       DECIMAL (18, 2) NOT NULL,
    [FacebookKey]         NVARCHAR (500)  NULL,
    [FacebookLink]        NVARCHAR (500)  NULL,
    [TwitterLink]         NVARCHAR (500)  NULL,
    [PinterestLink]       NVARCHAR (500)  NULL,
    [GooglePlusLink]      NVARCHAR (500)  NULL,
    [AccessCodeText]      NVARCHAR (500)  NULL,
    [MailChimpListID]     NCHAR (100)     NULL,
    [BankStatementName]   NVARCHAR (13)   NULL,
    [ServiceAccountId]    INT             NOT NULL,
    [EarningsExchange]    DECIMAL (18, 2) NULL,
    [RedemptionExchange]  DECIMAL (18, 2) NULL,
    [CdnUrlBase]          NVARCHAR (200)  NULL,
    CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED ([ClientId] ASC),
    CONSTRAINT [FK_Client_ClientAccessType] FOREIGN KEY ([ClientAccessTypeId]) REFERENCES [dbo].[ClientAccessType] ([ClientAccessTypeId]),
    CONSTRAINT [FK_Client_ClientLayoutTheme] FOREIGN KEY ([ClientLayoutThemeId]) REFERENCES [dbo].[ClientLayoutTheme] ([ClientLayoutThemeId]),
    CONSTRAINT [FK_Client_ClientProgramType] FOREIGN KEY ([ClientProgramTypeId]) REFERENCES [dbo].[ClientProgramType] ([ClientProgramTypeId]),
    CONSTRAINT [FK_Client_ClientRewardType] FOREIGN KEY ([ClientRewardTypeId]) REFERENCES [dbo].[ClientRewardType] ([ClientRewardTypeId]),
    CONSTRAINT [FK_Client_ClientType] FOREIGN KEY ([ClientTypeId]) REFERENCES [dbo].[ClientType] ([ClientTypeId])
);

